plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "maven-publish"
    id 'fabric-loom' version '1.0-SNAPSHOT'
}

base {
    archivesName = project.modName
}

version = project.modVersion
group = project.mavenGroup

loom {
    accessWidenerPath = file("src/main/resources/${project.modId}.accesswidener")

}

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven { url "https://maven.terraformersmc.com/releases/" }
    maven { url = "https://mvn.devos.one/snapshots/" }
    maven { url ="https://repo1.maven.org/maven2/"}
    maven { url = "https://jitpack.io/" }
    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

configurations {
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
}

dependencies {
        mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${project.parchment_version}@zip")
    } 

    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.3.6")))
    modImplementation(include("com.tterrag.registrate_fabric:Registrate:${project.registrate_version}"))
            {exclude group: "com.github.llamalad7.mixinextras" }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    // Minecraft 1.18 (1.18-pre2) upwards uses Java 17.
    it.options.release = 17
}

processResources {
    inputs.property "mod_id", modId
    inputs.property "mod_version", modVersion
    inputs.property "mod_name", modName
    inputs.property "mod_description", modName
    inputs.property "archives_base_name", modName

    inputs.property "minecraft_version", minecraft_version


    filesMatching("fabric.mod.json") {
        expand "mod_version": modVersion,
                "mod_id": modId,
                "mod_name": modName,
                "mod_description": modName,
                "archives_base_name": modName,

                "minecraft_version": minecraft_version
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    withSourcesJar()
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

jar {
    from('LICENSE') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}